name: Build CMIP6 Zarr from ESGF

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: "instance_id"
        default: "{MIP_ERA}.{ACTIVITY_ID}.{INSTITUTION_ID}.{SOURCE_ID}.{EXPERIMENT_ID}.{MEMBER_ID}.{TABLE_ID}.{VARIABLE_ID}.{GRID_LABEL}.{VERSION}"
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install pangeo_forge_recipes
    - run: python zarr_from_esgf.py ${{ github.event.inputs.instance_id }}
